#!/bin/bash

jpackage_command=jpackage

make createjar
$jpackage_command -i jar/ -n FidoCadJ --icon FidoCadJ.icns  --copyright "Davide Bucci, Manuel Finessi and many others"   --description "A multiplatform vector drawing software" --main-class fidocadj.FidoMain   --app-version 1.24.9 --main-jar fidocadj.jar
